#!/usr/bin/env bash

libraryfolders="${HOME}/.steam/steam/steamapps/libraryfolders.vdf"

[[ ! -e "${libraryfolders}" ]] && {
	echo "${libraryfolders} Não encontrado, Steam instalada?"
	exit 1
}

for librarys in $(grep path "${libraryfolders}" | awk -F' ' '{print $2}');do
	[[ ! -e "${librarys//\"/}/steamapps/compatdata" ]] && continue
	for pfx in $(ls "${librarys//\"/}/steamapps/compatdata");do
		grep -Poz '"apps"\s*\{\K([^}]*)' "${libraryfolders}" | awk -F' ' '{print $1}' | grep -qo "${pfx}" || {
			size=$(du -sh "${librarys//\"/}/steamapps/compatdata/${pfx}" | awk -F' ' '{print $1}')
			echo "Apagando: ${librarys//\"/}/steamapps/compatdata/${pfx}		Liberado: ${size}"
			rm -rf "${librarys//\"/}/steamapps/compatdata/${pfx}"
		}
	done
done
